[package]
name = "chust"
version = "0.1.0"
edition = "2024"
default-run = "perf"

[dependencies]
bitvec = "1"
thiserror = "2.0.17"
rand = "0.9.2"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "bench"
harness = false

[profile.test]
opt-level = 3

[profile.release]
debug = true
