[package]
name = "chust_uci"
version = "0.1.0"
edition = "2024"

[dependencies]
chust_engine = { path = "../engine" }
clap = { version = "4.5.54", default-features = false, features = [
    "std",
    "error-context",
    "derive",
] }
